theme: jekyll-theme-chirpy

lang: ko
timezone: Asia/Seoul

title: gyeo-log
tagline: 겨의 성장 일지
description: >-
  

url: "https://gyeore-log.github.io"
baseurl: "/gyeo-log"

github:
  username: gyeore-log

social:
  name: 이겨레
  email: gyaon901@naver.com
  links:
    - https://github.com/gyeore-log

theme_mode: auto  # 또는 dark

toc: true

paginate: 10
